### ISSUE TITLE
Can't install on python 3.9

### ISSUE THREAD

**Issue by rainzee** [pyos/libcno#8]

**Comment by pyos** [comment]
I don't have 3.9, but seems to install fine on 3.10 for me (though fails with a couple TypeErrors due to `loop` parameters no longer existing in `asyncio.Event` and `asyncio.Channel`). Did you install cffi first? That's due to the package not being on pypi I think, pip needs to load setup.py to read dependencies in that case but setup.py needs cffi to call `setup` with the right arguments.

**Comment by rainzee** [comment]
First of all thanks for your reply, I installed cffi, I don't know much about C and C++, but I presume that the installation may have failed due to my lack of Gcc compilation environment? This exception seems to be caused by Subprocess, so you can see if this is the case
![proff](https://user-images.githubusercontent.com/4585440/159161870-c8e571b4-e6fb-4c4f-a7ae-4f64f35fb07c.png)

**Comment by pyos** [comment]
Yes, you need some sort of C compiler. Probably MSVC.

**Comment by rainzee** [comment]
So what should i install
